stages:
  - build
  - release

build:
  stage: build
  tags:
    - k8s-root
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" --build-arg NGINX_CONFIG=nginx_conf/default.conf .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    - mkdir .images
    - echo "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" > .images/app
  artifacts:
    paths:
      - .images/app
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

.release:
  stage: release
  image: registry.met.no/k8s/tools/kustomize-cd:0.4.0
  tags:
    - k8s-unpriv
  variables:
    EXCLUDE_MAINTAINERS: '["miguelsn", "audunmg", "sebastianj"]'
    ENVIRONMENT: 'staging'
    AUTO_RELEASE: 'true'
  script:
    - 'echo app.gitlab.com/app: ${CI_PROJECT_PATH_SLUG}'
    - 'echo app.gitlab.com/env: ${CI_ENVIRONMENT_SLUG}'
    - release --repo https://gitlab.met.no/tjenester/annotated-atlas.git
      --access-token "${TJENESTE_ACCESS_TOKEN}"
      --automatic "$AUTO_RELEASE"
      --environment "$ENVIRONMENT"
      --updates-dir .images
      --exclude-maintainers "$EXCLUDE_MAINTAINERS"

staging:
  extends: .release
  variables:
    ENVIRONMENT: 'staging'
    AUTO_RELEASE: 'true'
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

production:
  extends: .release
  variables:
    ENVIRONMENT: 'production'
    AUTO_RELEASE: 'false'
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - package.json

