image:
  name: node:16

stages:
  - setup
  - test
  - build

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

setup:
  stage: setup
  tags:
    - k8s-unpriv
  script:
    - npm ci
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    expire_in: 2h
    paths:
      - node_modules

format-check:
  stage: test
  tags:
    - k8s-unpriv
  script:
    - npm run format:check

npm-test:
  stage: test
  tags:
    - k8s-unpriv
  script:
    - npm run test

build-prod:
  stage: build
  variables:
    REGISTRY_IMAGE: '${CI_REGISTRY_IMAGE}'
    DOCKERFILE: Dockerfile
    BUILD_CONTEXT_DIR: .
  tags:
    - k8s-root
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${REGISTRY_IMAGE}:${CI_COMMIT_TAG} -f ${DOCKERFILE} ${BUILD_CONTEXT_DIR}
    - docker push ${REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - mkdir .images
    - echo "${REGISTRY_IMAGE}:${CI_COMMIT_TAG}" > .images/${CI_JOB_NAME}
  artifacts:
    paths:
      - .images/${CI_JOB_NAME}
