stages:
  - build
  - release

build:
  stage: build
  variables:
    REGISTRY_IMAGE: '${CI_REGISTRY_IMAGE}'
    DOCKERFILE: Dockerfile
    BUILD_CONTEXT_DIR: .
  tags:
    - k8s-root
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${REGISTRY_IMAGE}:${CI_COMMIT_TAG} -f ${DOCKERFILE} ${BUILD_CONTEXT_DIR}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  rules: &buildrules
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]/'

tjenester/annotated-atlas:
  stage: release
  rules: *buildrules
  variables:
    UPSTREAM_CI_COMMIT_SHA: "${CI_COMMIT_SHA}"
    UPSTREAM_CI_PROJECT_PATH: "${CI_PROJECT_PATH}"
    UPSTREAM_CI_PROJECT_URL: "${CI_PROJECT_URL}"
    UPSTREAM_IMAGES: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  trigger: tjenester/annotated-atlas