image:
  name: node:16

stages:
  - test
  - build

npm-test:
  stage: test
  tags:
    - k8s-root
  script:
    - npm install
    - npm run test

build-prod:
  stage: build
  tags:
    - k8s-root
  script:
    - npm install
    - npm run build

.build-docker:
  stage: build
  tags:
    - k8s-root
  script:
    - docker build -t react-boilerplate .
